include(Compiler/CMakeCommonCompilerMacros)

##
# features for the Fujitsu compiler
#

# feature flags
set(CMAKE_CXX_VERBOSE_FLAG "-###")
set(CMAKE_CXX_COMPILE_OPTIONS_PIC "-fPIC")
set(CMAKE_CXX_COMPILE_OPTIONS_PIE "-fPIE")
set(CMAKE_CXX_COMPILE_OPTIONS_VISIBILITY "-fvisibility=")
set(CMAKE_SHARED_LIBRARY_CXX_FLAGS "-fPIC")
set(CMAKE_SHARED_LIBRARY_CREATE_CXX_FLAGS "-shared")

set(CMAKE_CXX_LINKER_WRAPPER_FLAG "-Wl,")
set(CMAKE_CXX_LINKER_WRAPPER_FLAG_SEP ",")

# initial configuration flags
string(APPEND CMAKE_CXX_FLAGS_INIT " ")
string(APPEND CMAKE_CXX_FLAGS_DEBUG_INIT " -g -O0")
string(APPEND CMAKE_CXX_FLAGS_RELEASE_INIT " -O3 -DNDEBUG")
string(APPEND CMAKE_CXX_FLAGS_RELWITHDEBINFO_INIT " -O2 -g -DNDEBUG")

# standards
set(CMAKE_CXX98_STANDARD_COMPILE_OPTION "-std=c++98")
set(CMAKE_CXX98_EXTENSION_COMPILE_OPTION "-std=gnu++98")
set(CMAKE_CXX03_STANDARD_COMPILE_OPTION "-std=c++03")
set(CMAKE_CXX03_EXTENSION_COMPILE_OPTION "-std=gnu++03")
set(CMAKE_CXX11_STANDARD_COMPILE_OPTION "-std=c++11")
set(CMAKE_CXX11_EXTENSION_COMPILE_OPTION "-std=gnu++11")
set(CMAKE_CXX14_STANDARD_COMPILE_OPTION "-std=c++14")
set(CMAKE_CXX14_EXTENSION_COMPILE_OPTION "-std=gnu++14")
set(CMAKE_CXX98_STANDARD_LINK_OPTION "-std=c++98")
set(CMAKE_CXX98_EXTENSION_LINK_OPTION "-std=gnu++98")
set(CMAKE_CXX03_STANDARD_LINK_OPTION "-std=c++03")
set(CMAKE_CXX03_EXTENSION_LINK_OPTION "-std=gnu++03")
set(CMAKE_CXX11_STANDARD_LINK_OPTION "-std=c++11")
set(CMAKE_CXX11_EXTENSION_LINK_OPTION "-std=gnu++11")
set(CMAKE_CXX14_STANDARD_LINK_OPTION "-std=c++14")
set(CMAKE_CXX14_EXTENSION_LINK_OPTION "-std=gnu++14")

set(CMAKE_CXX_CREATE_PREPROCESSED_SOURCE "<CMAKE_CXX_COMPILER> <DEFINES> <INCLUDES> <FLAGS> -E <SOURCE> > <PREPROCESSED_SOURCE>")
set(CMAKE_CXX_CREATE_ASSEMBLY_SOURCE "<CMAKE_CXX_COMPILER> <DEFINES> <INCLUDES> <FLAGS> -S <SOURCE> -o <ASSEMBLY_SOURCE>")

__compiler_check_default_language_standard(CXX 7 11)
